Repository weady-umc/weady-iOS, pull requests merged in 2025-08, with the labels that each got.

#60 [Feat/#58] NavigationStack 관련 파일 수정
  weady/weady.xcodeproj/project.pbxproj
  weady/weady/Resources/Assets.xcassets/Weadyboard/plusicon.imageset/plusicon 2.pdf
  weady/weady/Resources/Assets.xcassets/Weadyboard/post.imageset/post 2.pdf
  weady/weady/Sources/Common/Components/AppRootView.swift
  weady/weady/Sources/Common/Navigation/AppRootView.swift
  weady/weady/Sources/Common/Navigation/AppRoute.swift
  weady/weady/Sources/Common/Navigation/AppTabController.swift
  weady/weady/Sources/Common/Navigation/BaseTabContainerView.swift
  weady/weady/Sources/Common/Navigation/BaseTabScreen.swift
  weady/weady/Sources/Common/Navigation/BaseTabView.swift
  weady/weady/Sources/Common/Navigation/HomeFlowHost.swift
  weady/weady/Sources/Common/Navigation/MyPageFlowHost.swift
  weady/weady/Sources/Common/Navigation/NavigationRouter.swift
  weady/weady/Sources/Common/Navigation/Route.swift
  weady/weady/Sources/Common/Navigation/TabType.swift
  weady/weady/Sources/Common/Navigation/WeadyboardFlowHost.swift
  weady/weady/Sources/Common/Navigation/WeadyboardRouteBridge.swift
  weady/weady/Sources/Common/Navigation/WeadychiveFlowHost.swift
  weady/weady/Sources/Feature/Weadyboard/Basic/Views/WeadyboardFilterSheet.swift
  weady/weady/Sources/Feature/Weadyboard/Basic/Views/WeadyboardView.swift
  weady/weady/Sources/Feature/Weadychive/Views/WeadychiveView.swift
  weady/weady/Sources/Feature/Weather/Views/WeatherHomeView.swift
  weady/weady/Sources/Feature/Weather/Views/WeatherLocationAddView.swift
  weady/weady/Sources/Feature/Weather/Views/WeatherLocationView.swift
  weady/weady/Sources/Feature/Weather/Views/WeatherSearchView.swift
  weady/weady/weadyApp.swift
Labels: Feature ✨, Bug 🐛

#81 [Feat/#71] 웨디보드 게시물 api 연결
  weady/weady.xcodeproj/project.pbxproj
  weady/weady/Resources/Assets.xcassets/Weadyboard/bookmark.imageset/bookmark.pdf
  weady/weady/Resources/Assets.xcassets/Weadyboard/bookmark_fill.imageset/Contents.json
  weady/weady/Resources/Assets.xcassets/Weadyboard/bookmark_fill.imageset/bookmark_fill.pdf
  weady/weady/Resources/Assets.xcassets/Weadyboard/post_deleteicon.imageset/Contents.json
  weady/weady/Resources/Assets.xcassets/Weadyboard/post_deleteicon.imageset/deleteicon.pdf
  weady/weady/Resources/Assets.xcassets/Weadyboard/updateicon.imageset/Contents.json
  weady/weady/Resources/Assets.xcassets/Weadyboard/updateicon.imageset/updateicon.pdf
  weady/weady/Service/Board/Request/BoardRequestDTOs.swift
  weady/weady/Service/Board/Response/BoardResponseDTOs.swift
  weady/weady/Service/Tag/EndPoints/BoardTagEndpoints.swift
  weady/weady/Service/Tag/Response/BoardTagResponseDTOs.swift
  weady/weady/Service/Tag/Services/BoardTagService.swift
  weady/weady/Sources/Feature/Auth/Views/PreferenceInputView.swift
  weady/weady/Sources/Feature/Auth/Views/StartView.swift
  weady/weady/Sources/Feature/Weadyboard/Basic/ViewModels/TagViewModel.swift
  weady/weady/Sources/Feature/Weadyboard/Post/Models/WeatherTag.swift
  weady/weady/Sources/Feature/Weadyboard/Post/ViewModels/WeadyboardPostViewModel.swift
  weady/weady/Sources/Feature/Weadyboard/Post/Views/WeadyboardActionButtonsView.swift
  weady/weady/Sources/Feature/Weadyboard/Post/Views/WeadyboardMyPostMoreActionSheet.swift
  weady/weady/Sources/Feature/Weadyboard/Post/Views/WeadyboardPostMoreActionSheet.swift
  weady/weady/Sources/Feature/Weadyboard/Post/Views/WeadyboardPostView.swift
  weady/weady/Sources/Feature/Weadyboard/Report/ViewModels/WeadyboardReportViewModel.swift
  weady/weady/Sources/Feature/Weadyboard/Report/Views/WeadyboardPostReportTopBar.swift
  weady/weady/Sources/Feature/Weadychive/ViewModel/WeadychiveViewModel.swift
  weady/weady/weadyApp.swift
Labels: Feature ✨, Bug 🐛, API 🌐

#121 [Fix] 디자인 피드백 반영
  weady/weady/Service/Board/Endpoints/BoardEndpoints.swift
  weady/weady/Service/Board/Request/BoardRequestDTOs.swift
  weady/weady/Service/Board/Services/BoardService.swift
  weady/weady/Service/User/Endpoints/UserEndpoints.swift
  weady/weady/Service/User/Request/UserRequestDTOs.swift
  weady/weady/Service/User/Response/UserResponseDTOs.swift
  weady/weady/Service/User/Services/UserService.swift
  weady/weady/Sources/Feature/Profile/MyPage/Models/MypageModel.swift
  weady/weady/Sources/Feature/Profile/MyPage/ViewModels/MypageViewModel.swift
  weady/weady/Sources/Feature/Profile/MyPage/Views/MyPageCalendar.swift
  weady/weady/Sources/Feature/Profile/MyPage/Views/MyPageCalenderDayCard.swift
  weady/weady/Sources/Feature/Profile/MyPage/Views/MyPageDateFilter.swift
  weady/weady/Sources/Feature/Profile/MyPage/Views/MyPageView.swift
  weady/weady/Sources/Feature/Profile/ProfileEdit/ViewModels/ProfileEditViewModel.swift
  weady/weady/Sources/Feature/Profile/ProfileEdit/Views/ProfileEditView.swift
  weady/weady/Sources/Feature/Weadyboard/Upload/Models/WeatherModel.swift
  weady/weady/Sources/Feature/Weadyboard/Upload/Models/_UploadModel.swift
  weady/weady/Sources/Feature/Weadyboard/Upload/ViewModels/UploadViewModel.swift
  weady/weady/Sources/Feature/Weadyboard/Upload/ViewModels/_UploadViewModel.swift
  weady/weady/Sources/Feature/Weadyboard/Upload/Views/_Upload/PhotoAddView.swift
  weady/weady/Sources/Feature/Weadyboard/Upload/Views/_Upload/ToggleBtn.swift
  weady/weady/Sources/Feature/Weadyboard/Upload/Views/_Upload/UploadView.swift
Labels: Design 🎨, Refactor ♻️

#130 [Feat/#116] 배포 설정 및 애플 로그인 연결
  weady/weady.xcodeproj/project.pbxproj
  weady/weady/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  weady/weady/Resources/Assets.xcassets/AppIcon.appiconset/weady_applogo.jpg
  weady/weady/Sources/Common/Utilities/AppleLoginManager.swift
  weady/weady/Sources/Feature/Auth/ViewModels/AppleLoginViewModel.swift
  weady/weady/Sources/Feature/Auth/Views/LoginView.swift
  weady/weady/weady.entitlements
Labels: Feature ✨

#137 #129 [Bug] 마이페이지 api 연결 오류 해결
  weady/weady/Sources/Feature/Profile/MyPage/Models/MypageModel.swift
  weady/weady/Sources/Feature/Profile/MyPage/ViewModels/MypageViewModel.swift
  weady/weady/Sources/Feature/Profile/MyPage/Views/MyPageCalendar.swift
  weady/weady/Sources/Feature/Profile/MyPage/Views/MyPageCalenderDayCard.swift
  weady/weady/Sources/Feature/Profile/MyPage/Views/MyPageView.swift
  weady/weady/Sources/Feature/Profile/MyPage/Views/MypageBoardDetailView.swift
  weady/weady/Sources/Feature/Profile/MyPage/Views/MypageBoardView.swift
Labels: Bug 🐛, Design 🎨, API 🌐

#138 [Feat/#128] 네이버 지도 길찾기 URL Scheme 연동
  weady/weady/Info.plist
  weady/weady/Service/Curation/Endpoints/CurationEndpoints.swift
  weady/weady/Service/Curation/Response/CurationResponseDTO.swift
  weady/weady/Service/Weadychive/Endpoints/WeadychiveEndpoints.swift
  weady/weady/Sources/Feature/Curation/Models/CurationModel.swift
  weady/weady/Sources/Feature/Curation/Views/DetailCurationView.swift
Labels: Feature ✨, Refactor ♻️

#139 [Bug/#131] 가입 유무에 따른 화면 전환
  weady/weady/Info.plist
  weady/weady/Service/User/Endpoints/OnboardingEndpoints.swift
  weady/weady/Service/User/Request/OnboardingRequestDTOs.swift
  weady/weady/Service/User/Response/OnboardingResponseDTOs.swift
  weady/weady/Service/User/Services/OnboardingServices.swift
  weady/weady/Sources/Common/Navigation/AppRootView.swift
  weady/weady/Sources/Common/Navigation/BaseTabScreen.swift
  weady/weady/Sources/Common/Navigation/HomeFlowHost.swift
  weady/weady/Sources/Common/Navigation/NavigationRouter.swift
  weady/weady/Sources/Common/Navigation/OnboardingFlowView.swift
  weady/weady/Sources/Common/Navigation/OnboardingStateStore.swift
  weady/weady/Sources/Common/Utilities/AuthManager.swift
  weady/weady/Sources/Feature/Auth/ViewModels/AppleLoginViewModel.swift
  weady/weady/Sources/Feature/Auth/ViewModels/LoginViewModel.swift
  weady/weady/Sources/Feature/Auth/ViewModels/StartViewModel.swift
  weady/weady/Sources/Feature/Auth/Views/GenderSelectionView.swift
  weady/weady/Sources/Feature/Auth/Views/LoginView.swift
  weady/weady/Sources/Feature/Auth/Views/NicknameInputView.swift
  weady/weady/Sources/Feature/Auth/Views/OnboardingView.swift
  weady/weady/Sources/Feature/Auth/Views/PreferenceInputView.swift
  weady/weady/Sources/Feature/Auth/Views/SplashView.swift
  weady/weady/Sources/Feature/Auth/Views/StartView.swift
  weady/weady/Sources/Feature/Auth/Views/StyleSelectionView.swift
  weady/weady/Sources/Feature/Auth/Views/TermsAgreementView.swift
  weady/weady/Sources/Feature/Clothes/Views/ClothingRecommendationView.swift
  weady/weady/Sources/Feature/Curation/Views/CurationView.swift
  weady/weady/Sources/Feature/Home/Views/HomeView.swift
  weady/weady/Sources/Feature/Weather/Views/WeatherHomeView.swift
  weady/weady/Sources/Feature/Weather/Views/WeatherLocationAddView.swift
  weady/weady/Sources/Feature/Weather/Views/WeatherLocationView.swift
  weady/weady/Sources/Feature/Weather/Views/WeatherSearchView.swift
Labels: Feature ✨, Bug 🐛

#156 [Bug/#148] 최종 수정사항
  weady/weady.xcodeproj/project.pbxproj
  weady/weady/Service/User/Services/OnboardingService.swift
  weady/weady/Sources/Common/Navigation/AppRootView.swift
  weady/weady/Sources/Common/Navigation/WeadyboardFlowHost.swift
  weady/weady/Sources/Feature/Auth/ViewModels/NicknameInputViewModel.swift
  weady/weady/Sources/Feature/Auth/ViewModels/StartViewModel.swift
  weady/weady/Sources/Feature/Auth/Views/NicknameInputView.swift
  weady/weady/Sources/Feature/Auth/Views/StartView.swift
  weady/weady/Sources/Feature/Setting/ViewModels/SettingViewModel.swift
  weady/weady/Sources/Feature/Setting/Views/SettingView.swift
  weady/weady/Sources/Feature/Weadyboard/Post/Views/WeadyboardPostCardView.swift
  weady/weady/Sources/Feature/Weadyboard/Upload/Views/_Upload/UploadView.swift
Labels: Feature ✨, Bug 🐛, API 🌐

#162 [Desing/#141] 웨디카이브 게시물 진입
  weady/weady/Sources/Feature/Weadychive/Views/WeadychiveView.swift
Labels: Feature ✨, Bug 🐛

#165 [Design/#159] 최종 UI 수정사항 완료
  weady/Utilities/API.swift
  weady/Utilities/AppState.swift
  weady/Utilities/AppleLoginManager.swift
  weady/Utilities/AuthManager.swift
  weady/Utilities/CommonResponseDTOs.swift
  weady/Utilities/DefaultNetworkManager.swift
  weady/Utilities/NetworkError.swift
  weady/Utilities/NetworkManager+Extensions.swift
  weady/Utilities/NetworkManager+Protocols.swift
  weady/weady.xcodeproj/project.pbxproj
  weady/weady/Resources/Assets.xcassets/Auth/onboarding1.imageset/onboarding1.pdf
  weady/weady/Resources/Assets.xcassets/Auth/onboarding2.imageset/onboarding2.pdf
  weady/weady/Resources/Assets.xcassets/Auth/onboarding3.imageset/onboarding3.pdf
  weady/weady/Resources/Assets.xcassets/Auth/onboarding4.imageset/onboarding4.pdf
  weady/weady/Resources/Assets.xcassets/Auth/onboarding5.imageset/onboarding5.pdf
  weady/weady/Sources/Feature/Auth/Views/LoginView.swift
  weady/weady/Sources/Feature/Weadyboard/Basic/Views/WeadyboardView.swift
  weady/weady/Sources/Feature/Weadyboard/Post/Views/WeadyboardPostCommentSheet.swift
Labels: Feature ✨, Bug 🐛
